version: "3"

networks:
  loki:

volumes:
  log-data:
    driver: local

services:
  flog-log:
    image: mingrammer/flog
    container_name: flog-log
    command: "-f json -t log -l -w -d 5s -o /etc/data/data.log"
    volumes:
      - log-data:/etc/data

  fluent-bit:
    image: fluent/fluent-bit
    container_name: fluent-bit
    volumes:
      - ./fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
      - log-data:/etc/data
    depends_on:
      - loki
    networks:
      - loki

  loki:
    image: grafana/loki:2.7.0
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - loki
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
#    entrypoint:
#    - sh
#    - -euc
#    - |
#      mkdir -p /etc/grafana/provisioning/datasources
#      cat &lt; /etc/grafana/provisioning/datasources/ds.yaml
#      apiVersion: 1
#      datasources:
#      - name: Loki
#        type: loki
#        access: proxy
#        orgId: 1
#        url: http://loki:3100
#        basicAuth: false
#        isDefault: true
#        version: 1
#        editable: true
#      EOF
#      /run.sh